on:
  push:
  pull_request:

jobs:
  conan_cmake_lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Conan Create
        run: |
          cd recipes/cmake_lib
          conan create . 
          # conan upload <package_name>/* --all -r <myremote> -c

  conan_date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Conan Create
        run: |
          cd recipes/date
          conan create . --version=3.0.1 --user=ftena --channel=main \
          -pr:h=../../profiles/gcc11_cxx14_release \
          -pr:b=../../profiles/gcc11_cxx14_release --build=missing
          # conan upload <package_name>/* --all -r <myremote> -c

  conan_date_onlyheader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Conan Create
        run: |
          cd recipes/date-onlyheader
          conan create . --version=3.0.1 --user=ftena --channel=main \
          -pr:h=../../profiles/gcc11_cxx14_release \
          -pr:b=../../profiles/gcc11_cxx14_release
          # conan upload <package_name>/* --all -r <myremote> -c

  conan_spdlog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Conan Create
        run: |
          cd recipes/spdlog
          conan create . --version=1.11.0 --user=ftena --channel=main \
          -pr:h=../../profiles/gcc11_cxx14_release \
          -pr:b=../../profiles/gcc11_cxx14_release
          # conan upload <package_name>/* --all -r <myremote> -c

  conan_gtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - ../../profiles/gcc11_cxx14_debug
          - ../../profiles/gcc11_cxx14_release
          - ../../profiles/gcc13_cxx14_debuge
          - ../../profiles/gcc13_cxx14_release

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Conan Create
        working-directory: recipes/gtest
        run: |
          conan create . --version=1.16.0 --user=ftena --channel=main \
            -pr:h=${{ matrix.profile }} \
            -pr:b=${{ matrix.profile }} \
          # conan upload <package_name>/* --all -r <myremote> -c